### PR TITLE
LBY - Configurable Minigames

### PR DESCRIPTION
**Pull request by Fito**
Allows for the configuration of minigames to run:
- Adds minigames.conf file which contains the name and location of the
  minigames.
- Modifies MiniGameServers.java to load minigame configuration data
  from minigames.conf

### CODE REVIEW

**Comment by Fito** [comment]
@jensvdh @rujoota 
Please review my pull request.
I added a config file where we can specify the location of the minigames.
I guess this file doesn't necessarily have to be checked in, since some people might want to have their minigame jars in different locations, but at least now we don't have to change code to add or remove minigames.

**Comment by jensvdh** [comment]
Hey it looks like there are some merge conflicts with development.

**Comment by Fito** [comment]
@jensvdh I fixed the merge conflict.

**Comment by jensvdh** [comment]
@Fito Looks good! Let's merge this into dev.

**Pull request merged**
